version: "3"
volumes:
  pubsub:
services:

  pubsub:
    image: google/cloud-sdk:269.0.0
    command: [gcloud, beta, emulators, pubsub, start, --data-dir=/data, "--host-port=0.0.0.0:8085", "--project=local"]
    volumes:
      - pubsub:/data
    ports:
      - 8085:8085

  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.0
    command:
      - --smallfiles
      - --wiredTigerCacheSizeGB=1.5
      - --bind_ip=0.0.0.0
      - --quiet
    environment:
      MONGO_INITDB_DATABASE: bluebudgetz
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-bluebudgetz-db.js
    ports:
      - 27017:27017

  gate:
    build:
      context: ../gate
      dockerfile: build/Dockerfile
    depends_on:
      - mongo
      - redis
      - pubsub
    environment:
      DB_MONGODB_URI: mongodb://mongo:27017
      DB_REDIS_URI: redis:6379
      HTTP_CORS_ALLOW_ORIGIN: http://localhost:3000
      LOG_PRETTY: "yes"
      PUBSUB_DEAD_LETTERBOX_TOPIC: dead-letter-box
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_MAX_PROCESS_FAILURES: "1"
      PUBSUB_TX_SUBSCRIPTION: local/transactions/transactions-gate
    ports:
      - 3001:3001
      - 3002:3002

#  front:
#    build:
#      context: ../front
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
