version: "3.7"

volumes:
  pubsub:

services:

  neo4j:
    build:
      context: ../neo4j
      dockerfile: Dockerfile
    ports: [7473:7473, 7474:7474, 7687:7687]

  gate:
    build:
      context: ../gate
      dockerfile: build/dockerfile
    depends_on: [neo4j]
    environment:
      http_cors_allow_origin: http://localhost:3000
      log_pretty: "yes"
    ports: [3001:3001, 3002:3002]

#  front:
#    build:
#      context: ../front
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#      google_application_credentials: ../etc/bluebudgetz-sa-key.json
#      pubsub_dead_letterbox_topic: dead-letter-box
#      pubsub_emulator_host: pubsub:8085
#      pubsub_max_process_failures: "1"
#      pubsub_tx_subscription: local/transactions/transactions-gate
#  pubsub:
#    image: google/cloud-sdk:269.0.0
#    command: [gcloud, beta, emulators, pubsub, start, --data-dir=/data, "--host-port=0.0.0.0:8085", "--project=local"]
#    volumes:
#      - pubsub:/data
#    ports:
#      - 8085:8085

#  redis:
#    image: redis:5.0
#    ports:
#      - 6379:6379
