version: "3"
services:

  db:
    image: postgres:11.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
      POSTGRES_INITDB_ARGS: "--auth=trust --auth-host=trust --auth-local=trust"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 3100:8080

  pubsub:
    image: google/cloud-sdk:241.0.0
    volumes:
      - pubsub:/data
    command: [gcloud, beta, emulators, pubsub, start, --data-dir=/data, "--host-port=0.0.0.0:8085"]
    ports:
      - 8085:8085

  redis:
    image: redis:5.0
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  pubsub:
  redis:
